{{- with .Values.homeassistant.persistence }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-config
  labels:
    {{- include "homeassistant.labels" $ | nindent 4 }}
    {{- if .labels }}
    {{- .labels | toYaml | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    - {{ .accessMode }}
  resources:
    requests:
      storage: {{ .size }}
{{- end }}
