{{- with .Values.homeassistant.persistence }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-config
  labels:
    {{- include "homeassistant.labels" $ | nindent 4 }}
spec:
  storageClassName: {{ .storageClass }}
  accessModes:
    - {{ .accessMode }}
  resources:
    requests:
      storage: {{ .size }}
{{- end }}
