apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data
  labels:
    {{- include "mosquitto.labels" $ | nindent 4 }}
spec:
  {{- with .Values.mosquitto.persistence }}
  accessModes:
    - {{ .accessMode }}
  resources:
    requests:
      storage: {{ .size }}
  {{- end }}
