{{- with .Values.zigbee2mqtt }}
{{- if .enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zigbee2mqtt
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      nodeSelector:
        {{ toYaml .nodeSelector | nindent 8 }}
      containers:
        - name: zigbee2mqtt
          image: "{{ .image.repository }}:{{ .image.tag }}"
          env:
            - name: TZ
              value: {{ $.Values.tz }}
          envFrom:
            - configMapRef:
                name: zigbee2mqtt-config
            - secretRef:
                name: zigbee2mqtt-secret
          securityContext:
            privileged: true
          ports:
            - name: http-z2m-pod
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: http-z2m-pod
          volumeMounts:
            - name: data
              mountPath: /app/data
            - name: udev
              mountPath: /run/udev
              readOnly: true
            - name: serial
              mountPath: /dev/ttyACM0
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: zigbee2mqtt-data
        - name: udev
          hostPath:
            path: /run/udev
        - name: serial
          hostPath:
            path: {{ required "zigbee2mqtt.serial.path" .serial.path }}
{{- end }}
{{- end }}
