{{- with .Values.zigbee2mqtt }}
{{- if .enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: zigbee2mqtt-secret
  labels:
    app: zigbee2mqtt
stringData:
  {{- with .mqtt }}
  ZIGBEE2MQTT_CONFIG_MQTT_USER: {{ required "zigbee2mqtt.mqtt.username" .username }}
  ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: {{ required "zigbee2mqtt.mqtt.password" .password }}
  {{- end }}
{{- end }}
{{- end }}
