apiVersion: v1
kind: Secret
metadata:
  name: zigbee2mqtt-secret
  labels:
    app: zigbee2mqtt
stringData:
  {{- with .Values.zigbee2mqtt.mqtt }}
  ZIGBEE2MQTT_CONFIG_MQTT_USER: {{ .username }}
  ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: {{ required "ZigBee2MQTT password" .password }}
  {{- end }}
