{{- with .Values.zigbee2mqtt }}
{{- if .enabled }}
apiVersion: v1
kind: Service
metadata:
  name: zigbee2mqtt
  labels:
    app: zigbee2mqtt
spec:
  selector:
    app: zigbee2mqtt
  ports:
    - name: http-z2m-svc
      port: 8080
      targetPort: http-z2m-pod
{{- end }}
{{- end }}
