apiVersion: apps/v1
{{- with .Values.homeassistant }}
kind: Deployment
metadata:
  name: homeassistant
spec:
  replicas: 1
  {{- with .serial.nodeSelector }}
  {{- if . }}
  nodeSelector:
    {{ . | toYaml | nindent 4 }}
  {{- end }}
  {{- end }}
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
        - name: homeassistant
          {{- with .image }}
          image: "{{ .repository }}:{{ .tag | default $.Chart.AppVersion }}"
          {{- end }}
          ports:
            - name: http-ha-pod
              containerPort: 8123
          livenessProbe:
            httpGet:
              path: /
              port: http-ha-pod
          volumeMounts:
            - name: config
              mountPath: /config
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
            {{-  if .serial.path }}
            - name: serial
              mountPath: /dev/ttyACM0
            {{- end }}
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: homeassistant-config
        - name: localtime
          hostPath:
            path: /etc/localtime
        {{- with .serial.path }}
        {{- if . }}
        - name: serial
          hostPath:
            path: {{ . }}
        {{- end }}
        {{- end }}
{{- end }}
