apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
      - name: homeassistant
        {{- with .Values.homeassistant.image }}
        image: "{{ .repository }}:{{ .tag | default $.Chart.AppVersion }}"
        {{- end }}
        ports:
        - name: http-ha-pod
          containerPort: 8123
        resources: {}
        volumeMounts:
        - name: config
          mountPath: /config
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: homeassistant-config
      - name: localtime
        hostPath:
          path: /etc/localtime
