{{- with .Values.homeassistant }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      hostNetwork: {{ .hostNetwork }}
      dnsPolicy: {{ .dnsPolicy }}
      containers:
        - name: homeassistant
          {{- with .image }}
          image: "{{ .repository }}:{{ .tag | default $.Chart.AppVersion }}"
          {{- end }}
          ports:
            - name: http-ha-pod
              containerPort: 8123
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          livenessProbe:
            {{- toYaml .livenessProbe | nindent 12 }}
          env:
            - name: TZ
              value: {{ $.Values.tz }}
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: homeassistant-config
{{- end }}
