{{- with .Values.homeassistant }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      {{- if .serial.nodeSelector }}
      nodeSelector: {{ toYaml .serial.nodeSelector | nindent 8 }}
      {{- end }}
      hostNetwork: {{ .hostNetwork }}
      dnsPolicy: {{ .dnsPolicy }}
      containers:
        - name: homeassistant
          {{- with .image }}
          image: "{{ .repository }}:{{ .tag | default $.Chart.AppVersion }}"
          {{- end }}
          ports:
            - name: http-ha-pod
              containerPort: 8123
          livenessProbe:
            httpGet:
              path: /
              port: http-ha-pod
          env:
            - name: TZ
              value: {{ $.Values.tz }}
          volumeMounts:
            - name: config
              mountPath: /config
            {{-  if .serial.path }}
            - name: serial
              mountPath: /dev/ttyACM0
            {{- end }}
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: homeassistant-config
        {{- with .serial.path }}
        {{- if . }}
        - name: serial
          hostPath:
            path: {{ . }}
        {{- end }}
        {{- end }}
{{- end }}
