apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-config
  labels:
    app: homeassistant
spec:
  {{- with .Values.homeassistant.persistence }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .size }}
  {{- end }}
