### General ###
tz: ""


### Home Assistant ###
homeassistant:

  image:
    repository: homeassistant/home-assistant
    tag: ""  # default: .Chart.AppVersion

  ingress:
    enabled: false
    className: ""
    annotations: {}
    host: ""
    tls: []

  persistence:
    accessMode: ReadWriteOnce
    size: 8Gi

  mqtt:
    username: ""
    # password not needed - set in Home Assistant UI
    mosquitto_hash: ""

  serial:
    nodeSelector: {}
    path: ""


### Mosquitto ###
mosquitto:

  image:
    repository: eclipse-mosquitto
    tag: "2.0.20"

  persistence:
    accessMode: ReadWriteOnce
    size: 256Mi


### ZigBee2MQTT ###
zigbee2mqtt:

  enabled: false

  image:
    repository: koenkk/zigbee2mqtt
    tag: "1.41.0"

  ingress:
    enabled: false
    className: ""
    annotations: {}
    host: ""
    tls: []

  persistence:
    accessMode: ReadWriteOnce
    size: 1Gi

  mqtt:
    username: ""
    password: ""
    mosquitto_hash: ""

  serial:
    nodeSelector: {}
    path: ""


### Ring MQTT ###
ringMqtt:

  enabled: false

  image:
    repository: tsightler/ring-mqtt
    tag: "5.7.3"

  persistence:
    accessMode: ReadWriteOnce
    size: 256Mi

  mqtt:
    username: ""
    password: ""
    mosquitto_hash: ""


extraObjects: {}
