### General ###
tz: ""


### Home Assistant ###
homeassistant:

  image:
    repository: homeassistant/home-assistant
    tag: ""  # default: .Chart.AppVersion

  ingress:
    enabled: false
    className: ""
    annotations: {}
    host: ""
    tls: []

  persistence:
    size: 8Gi

  hostNetwork: false

  dnsPolicy: Default

  securityContext: {}
    # allowPrivilegeEscalation: false
    # readOnlyRootFilesystem: true
    # seccompProfile:
    #   type: RuntimeDefault

  resources: {}
    # limits:
    #   cpu: 2000m
    #   memory: 2Gi
    # requests:
    #   cpu: 250m
    #   memory: 1Gi

  livenessProbe:
    httpGet:
      path: /
      port: http-ha-pod

  mqtt:
    username: ""
    # password not needed - set in Home Assistant UI
    mosquitto_hash: ""


### Mosquitto ###
mosquitto:

  image:
    repository: eclipse-mosquitto
    tag: "2.0.20"

  persistence:
    accessMode: ReadWriteOnce
    size: 256Mi


### ZigBee2MQTT ###
zigbee2mqtt:

  enabled: false

  image:
    repository: koenkk/zigbee2mqtt
    tag: "2.0.0"

  nodeSelector: {}

  ingress:
    enabled: false
    className: ""
    annotations: {}
    host: ""
    tls: []

  persistence:
    accessMode: ReadWriteOnce
    size: 1Gi

  mqtt:
    username: ""
    password: ""
    mosquitto_hash: ""

  serial:
    path: ""


### Ring MQTT ###
ringMqtt:

  enabled: false

  image:
    repository: tsightler/ring-mqtt
    tag: "5.7.3"

  persistence:
    accessMode: ReadWriteOnce
    size: 256Mi

  mqtt:
    username: ""
    password: ""
    mosquitto_hash: ""


extraObjects: {}
