{{- with .Values.ringMqtt }}
{{- if .enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ring-mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ring-mqtt
  template:
    metadata:
      labels:
        app: ring-mqtt
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/ring-mqtt/secret.yaml") $ | sha256sum }}
    spec:
      containers:
        - name: ring-mqtt
          image: "{{ .image.repository }}:{{ .image.tag }}"
          # ports:
          # - containerPort: 8554
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /data/config.json
              subPath: config.json
              readOnly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: ring-mqtt-data
        - name: config
          secret:
            secretName: ring-mqtt-config
{{- end }}
{{- end }}
