apiVersion: apps/v1
kind: Deployment
metadata:
  name: ring-mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ring-mqtt
  template:
    metadata:
      labels:
        app: ring-mqtt
    spec:
      containers:
      - name: homeassistant
        {{- with .Values.ringMqtt.image }}
        image: "{{ .repository }}:{{ .tag }}"
        {{- end }}
        # ports:
        # - containerPort: 8554
        volumeMounts:
        - name: data
          mountPath: /data
        - name: config
          mountPath: /data/config.json
          subPath: config.json
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: ring-mqtt-data
      - name: config
        secret:
          secretName: ring-mqtt-config
