{{- with .Values.ringMqtt }}
{{- if .enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ring-mqtt-data
spec:
  {{- with .persistence }}
  accessModes:
    - {{ .accessMode }}
  resources:
    requests:
      storage: {{ .size }}
  {{- end }}
{{- end }}
{{- end }}
