apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ring-mqtt-data
spec:
  {{- with .Values.ringMqtt.persistence }}
  accessModes:
    - {{ .accessMode }}
  resources:
    requests:
      storage: {{ .size }}
  {{- end }}
