{{- with .Values.ringMqtt }}
{{- if .enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: ring-mqtt-config
  labels:
    app: ring-mqtt
stringData:
  config.json: {{ "|-" }}
    {{- with .mqtt }}
    {{- $username := (required "ringMqtt.mqtt.username" .username) }}
    {{- $password := (required "ringMqtt.mqtt.password" .password) | urlquery }}
    {{- $url := printf "mqtt://%s:%s@mosquitto:1883" $username $password }}
    {{ dict "mqtt_url" $url "enable_modes" "true" | toJson }}
    {{- end }}
{{- end }}
{{- end }}
