apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-passwd
  labels:
    app: mosquitto
stringData:
  passwd: {{ "|-" }}
    {{- with .Values.homeassistant.mqtt }}
    {{ required "MQTT username for Home Assistant" .username }}
    {{- ":" }}
    {{- required "MQTT password for Home Assistant" .password }}
    {{- end }}
    {{- with .Values.zigbee2mqtt.mqtt }}
    {{ required "MQTT username for Zigbee2MQTT" .username }}
    {{- ":" }}
    {{- required "MQTT password for Zigbee2MQTT" .password }}
    {{- end }}
    {{- with .Values.ringMqtt.mqtt }}
    {{ required "MQTT username for ring-mqtt" .username }}
    {{- ":" }}
    {{- required "MQTT password for ring-mqtt" .password }}
    {{- end }}
