apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-passwd
  labels:
    app: mosquitto
stringData:
  passwd: {{ "|-" }}
    {{- with .Values.homeassistant.mqtt }}
    {{ required "homeassistant.mqtt.username" .username }}
    {{- ":" }}
    {{- required "homeassistant.mqtt.mosquitto_hash" .mosquitto_hash }}
    {{- end }}
    {{- with .Values.zigbee2mqtt }}
    {{- if .enabled }}
    {{- with .mqtt }}
    {{ required "zigbee2mqtt.mqtt.username" .username }}
    {{- ":" }}
    {{- required "zigbee2mqtt.mqtt.mosquitto_hash" .mosquitto_hash }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- with .Values.ringMqtt.mqtt }}
    {{ required "ringMqtt.mqtt.username" .username }}
    {{- ":" }}
    {{- required "ringMqtt.mqtt.mosquitto_hash" .mosquitto_hash }}
    {{- end }}
