apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-passwd
  labels:
    app: mosquitto
stringData:
  passwd: {{ "|-" }}
    {{- with .Values.homeassistant.mqtt }}
    {{ required "MQTT username for Home Assistant" .username }}
    {{- ":" }}
    {{- required "MQTT hash for Home Assistant" .mosquitto_hash }}
    {{- end }}
    {{- with .Values.zigbee2mqtt.mqtt }}
    {{ required "MQTT username for Zigbee2MQTT" .username }}
    {{- ":" }}
    {{- required "MQTT hash for Zigbee2MQTT" .mosquitto_hash }}
    {{- end }}
    {{- with .Values.ringMqtt.mqtt }}
    {{ required "MQTT username for ring-mqtt" .username }}
    {{- ":" }}
    {{- required "MQTT hash for ring-mqtt" .mosquitto_hash }}
    {{- end }}
