name: Lint, Test, and Publish Helm Charts

on:
  push:
    branches:
      - "**"
    paths:
      - "charts/**"
  pull_request:
    branches:
      - "**"

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Helm
      uses: azure/setup-helm@v3

    - name: Lint & Template Helm Charts
      run: |
        cd charts
        for dir in */; do
          echo "Linting $dir"
          helm lint "$dir"

          if [ -d "$dir/examples" ]; then
            for values_file in $dir/examples/*.yaml; do
              echo "Template $dir with $values_file"
              helm template "$dir" --values "$values_file"
            done
          fi
        done

  release:
    needs: lint-test
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          config: cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
